export const GAME_TITLE = "BLACKOUT";
export const MAX_PLAYERS = 10;
export const TEAM_SIZE = 5;
export const BOMB_PLANT_TIME = 4; // seconds
export const BOMB_DEFUSE_TIME = 7; // seconds
export const ROUND_TIME_LIMIT = 120; // seconds
export const DEFAULT_HEALTH = 100;
export const HEADSHOT_MULTIPLIER = 2.0;
export const ARMOR_DAMAGE_REDUCTION = 0.5; // 50% damage reduction
export const RELOAD_ANIMATION_TIME = 2; // seconds
export const MAX_AMMO = 30; // per magazine
export const TOTAL_AMMO = 90; // total ammo per player
export const ACCELERATION = 5; // units per second squared
export const FRICTION = 0.5; // friction coefficient for movement
export const JUMP_HEIGHT = 1.5; // units
export const SPRINT_MULTIPLIER = 1.5; // speed multiplier while sprinting
export const CROUCH_MULTIPLIER = 0.5; // speed multiplier while crouching
export const GAME_VERSION = "0.1.0";